import {
  NOTIFICATIONS_QUEUE,
  connectToChannel,
  sendNotificationsToQueue,
} from '@cowprotocol/notifications';
import { Notification } from '@cowprotocol/notifications';

const POST_TO_QUEUE_ACCOUNT = process.env.POST_TO_QUEUE_ACCOUNT;

it('Post to queue', async () => {
  if (!POST_TO_QUEUE_ACCOUNT) {
    return;
  }

  const message: Notification = {
    id: '1',
    title: 'My little test',
    message:
      "This message has been generated by postToQueueTest.test.ts (in BFF's apps/notification-producer).",
    account: POST_TO_QUEUE_ACCOUNT,
    url: 'https://swap.cow.fi/#/1/limit/WETH/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48?tab=all&page=1',
  };

  const { channel } = await connectToChannel({
    channel: NOTIFICATIONS_QUEUE,
  });

  sendNotificationsToQueue({
    channel,
    queue: NOTIFICATIONS_QUEUE,
    notifications: [message],
  });

  console.log(
    `✅ Posted a message to queue for account ${POST_TO_QUEUE_ACCOUNT}:\n${JSON.stringify(
      message,
      null,
      2
    )}`
  );
});
