import { PushNotification } from '@cowprotocol/notifications';
import { getPushNotificationsRepository } from '@cowprotocol/services';

const POST_TO_QUEUE_ACCOUNT = process.env.POST_TO_QUEUE_ACCOUNT;

it('Post to queue', async () => {
  console.log('POST_TO_QUEUE_ACCOUNT', POST_TO_QUEUE_ACCOUNT);
  if (!POST_TO_QUEUE_ACCOUNT) {
    return;
  }

  const pushNotificationsRepository = getPushNotificationsRepository();
  await pushNotificationsRepository.connect();

  const markdown = `\
**Testing PUSH notifications**

This \`message\` has been generated by [sendPush.test.ts](https://github.com/cowprotocol/bff/blob/main/apps/notification-producer/src/sendPush.test.ts) (in [BFF's](https://github.com/cowprotocol/bff) [apps/notification-producer](https://github.com/cowprotocol/bff/tree/main/apps/notification-producer)).

🐮 Have a nice day!`;

  const message: PushNotification = {
    id: '1',
    title: 'My little test',
    message: markdown,
    account: POST_TO_QUEUE_ACCOUNT,
    url: 'https://swap.cow.fi/#/1/limit/WETH/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48?tab=all&page=1',
  };

  await pushNotificationsRepository.send([message]);
  console.log(
    `✅ Posted a message to queue for account ${POST_TO_QUEUE_ACCOUNT}:\n${JSON.stringify(
      message,
      null,
      2
    )}`
  );
});
