name: 'Setup Dependencies'
description: 'Setup npmrc and node with yarn (assumes code is already checked out)'

runs:
  using: 'composite'
  steps:
    - name: Set up node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version: lts/*
        cache: yarn

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
