/**
 * Regenerates the CoinGecko asset platform list.
 *
 * Run by hand with `yarn gen:coingecko-platforms` when a new chain is added, and commit the result.
 * Deliberately NOT wired into `build`, `postinstall` or CI: the generated file is committed source,
 * so no build ever depends on CoinGecko being reachable.
 */
import { writeFileSync } from 'fs'
import { join } from 'path'

const ENDPOINT = '/api/v3/asset_platforms'
const PUBLIC_URL = `https://api.coingecko.com${ENDPOINT}`
const PRO_URL = `https://pro-api.coingecko.com${ENDPOINT}`
const OUTPUT_PATH = join(__dirname, '../libs/repositories/src/gen/coingecko/asset-platforms.ts')

interface AssetPlatformResponse {
  id: string
  chain_identifier: number | null
  native_coin_id?: string | null
}

async function main(): Promise<void> {
  const apiKey = process.env.COINGECKO_API_KEY
  const url = apiKey ? PRO_URL : PUBLIC_URL
  const response = await fetch(url, apiKey ? { headers: { 'x-cg-pro-api-key': apiKey } } : undefined)

  if (!response.ok) {
    throw new Error(`${url} returned ${response.status} ${response.statusText}`)
  }

  const platforms = (await response.json()) as AssetPlatformResponse[]

  if (!Array.isArray(platforms) || platforms.length === 0) {
    throw new Error(`Unexpected response from ${url}: ${JSON.stringify(platforms).slice(0, 200)}`)
  }

  // Sorted by id so regenerating only diffs what actually changed upstream
  const rows = platforms
    .filter((platform) => Boolean(platform.id))
    .sort((a, b) => a.id.localeCompare(b.id))
    .map(
      ({ id, chain_identifier, native_coin_id }) =>
        // JSON.stringify, not raw interpolation: these values become TypeScript source, so a quote
        // or backslash upstream would emit a file that does not compile
        `  { platform: ${JSON.stringify(id)}, chainId: ${chain_identifier ?? null}, nativeCoinId: ${
          native_coin_id ? JSON.stringify(native_coin_id) : null
        } },`
    )

  writeFileSync(
    OUTPUT_PATH,
    `/* eslint-disable */
/**
 * Generated by \`yarn gen:coingecko-platforms\`. Do not edit by hand.
 * Source: ${PUBLIC_URL}
 */

/** platform: CoinGecko asset platform id. chainId: EVM chain id, when CoinGecko publishes one.
 *  nativeCoinId: coin id of the platform's native currency, which is NOT the platform id. */
export const COINGECKO_ASSET_PLATFORMS: readonly {
  platform: string
  chainId: number | null
  nativeCoinId: string | null
}[] = [
${rows.join('\n')}
]
`
  )

  console.log(`Wrote ${platforms.length} asset platforms to ${OUTPUT_PATH}`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
